# Generated by Django 5.2.16 on 2026-07-26 14:50

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Short description shown under the title', max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Main article content')),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary — auto-generated from content if left empty', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('featured_image_caption', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('meta_title', models.CharField(blank=True, help_text='Auto-filled from title if empty', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Auto-filled from excerpt if empty', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on homepage / top of listing')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blogs.blogauthor')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['-publish_date'], name='blogs_blogp_publish_7b52a7_idx'), models.Index(fields=['slug'], name='blogs_blogp_slug_cd60a0_idx'), models.Index(fields=['is_published'], name='blogs_blogp_is_publ_ca7ab6_idx')],
            },
        ),
    ]
