# Generated by Django 5.2.16 on 2026-07-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Date the event took place — controls ordering')),
                ('summary', models.TextField(help_text='Short write-up shown beside the photo strip. 2–4 sentences works best.')),
                ('instagram_url', models.URLField(blank=True, help_text='Optional. Link to the Instagram reel or post for this event.')),
                ('location', models.CharField(blank=True, help_text="Optional. e.g. 'Rove Hotels, Dubai' or 'Meydan'", max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['-date'], name='blogs_event_date_132d12_idx'), models.Index(fields=['is_published'], name='blogs_event_is_publ_122e8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional. Used as the image alt text and shown in the lightbox.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blogs.event')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
