# Generated by Django 5.2.16 on 2026-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_event_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional. If set, this photo becomes a play button that opens the Instagram reel instead of the lightbox.'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
