"""
Django settings for space_smith project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECRET_KEY = 'django-insecure-cb%0&d6bnj_xb@ub9usps%3=@$i4cuigx2=^nf+q%+!em=%0eq'

# ====================
# CORE SETTINGS
# ====================

SECRET_KEY    = config('SECRET_KEY', default='your-secret-key-here')
DEBUG         = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,www.spacesmith.ae,spacesmith.ae').split(',')


CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://www.spacesmith.ae",
    "https://spacesmith.ae",
]

# ====================
# APPLICATIONS
# ====================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    
    # Third-party
    'django_ckeditor_5',
    
    # Local apps
    'main',
    'properties',
    'blogs',
]

SITE_ID = 1

# ====================
# MIDDLEWARE
# ====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'space_smith.urls'


# ====================
# SITE INFO
# ====================

SITE_NAME        = 'Spacesmith Real Estate'
SITE_URL         = config('SITE_URL', default='https://spacesmith.ae')
SITE_TAGLINE     = 'We Find Your Space'
SITE_DESCRIPTION = (
    'Spacesmith Real Estate LLC is a Dubai-based real estate consultancy specializing in '
    'residential and commercial property sales, leasing, portfolio management and '
    'investment advisory across the UAE.'
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',    # Added for media files
                'django.template.context_processors.static',   # Added for static files
                'main.context_processors.site_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'space_smith.wsgi.application'


# ====================
# DATABASE
# ====================

# DATABASES = {
#     'default': {
#         'ENGINE':   config('DB_ENGINE',   default='django.db.backends.sqlite3'),
#         'NAME':     config('DB_NAME',     default=str(BASE_DIR / 'db.sqlite3')),
#         'USER':     config('DB_USER',     default=''),
#         'PASSWORD': config('DB_PASSWORD', default=''),
#         'HOST':     config('DB_HOST',     default=''),
#         'PORT':     config('DB_PORT',     default=''),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE':   config('DB_ENGINE',   default='django.db.backends.postgresql'),
        'NAME':     config('DB_NAME'),
        'USER':     config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST':     config('DB_HOST',     default='localhost'),
        'PORT':     config('DB_PORT',     default='5432'),
    }
}


# ====================
# PASSWORD VALIDATION
# ====================
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ====================
# INTERNATIONALIZATION
# ====================
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ====================
# STATIC & MEDIA
# ====================

STATIC_URL = '/static/'
STATIC_ROOT      = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ====================
# CKEDITOR 5
# ====================

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # or "authenticated" or "any"

CKEDITOR_5_UPLOAD_PATH = 'uploads/'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', '|',
                'bulletedList', 'numberedList', '|',
                'blockQuote', 'code', '|',
                'link', 'uploadImage', '|',
                'insertTable', 'mediaEmbed', '|',
                'undo', 'redo',
            ]
        },
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4' },
            ]
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', 'toggleImageCaption',
                'imageStyle:inline', 'imageStyle:block', 'imageStyle:side',
                '|', 'linkImage',
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'height': 450,
        'width': '100%',
    }
}


# ====================
# CACHE
# ====================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'luxehaven-cache',
    }
}


# ====================
# PAGINATION
# ====================

PAGINATION = {
    'DEFAULT_PAGE_SIZE': 12,
    'ALLOWED_PAGE_SIZES': [6, 9, 12, 18, 24],
    'BLOG_PAGE_SIZE': 9,
}


# ====================
# CONTACT INFO
# ====================

CONTACT_EMAIL     = config('CONTACT_EMAIL',     default='hello@spacesmithrealestate.com')
ADMIN_EMAIL       = config('ADMIN_EMAIL',       default='hello@spacesmithrealestate.com')
CONTACT_PHONE     = config('CONTACT_PHONE',     default='+971 55 639 9212')   # display
CONTACT_PHONE_RAW = config('CONTACT_PHONE_RAW', default='971556399212')       # tel:/wa.me — no + or spaces
CONTACT_LANDLINE  = config('CONTACT_LANDLINE',  default='+971 4 327 9792')
WHATSAPP_NUMBER   = config('WHATSAPP_NUMBER',   default='971556399212')       # no +
CONTACT_ADDRESS   = '117, Royal Class Building, Dubai Investment Park First, Dubai'


# ====================
# EMAIL INFO
# ====================

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp-relay.brevo.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL', default='Spacesmith Real Estate <hello@spacesmithrealestate.com>')


# ====================
# SECURITY
# ====================

SECURE_BROWSER_XSS_FILTER   = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS             = 'SAMEORIGIN'
SECURE_REFERRER_POLICY      = 'same-origin'
CSRF_COOKIE_SECURE          = False
SESSION_COOKIE_SECURE       = False
SECURE_SSL_REDIRECT         = False
# for production only
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True

if not DEBUG:
    SECURE_HSTS_SECONDS            = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True
    SECURE_PROXY_SSL_HEADER        = ('HTTP_X_FORWARDED_PROTO', 'https')




# ====================
# LOGGING
# ====================

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'main':   {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'properties': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'blogs': {'handlers': ['console', 'file'],'level': 'INFO','propagate': False},
    },
}


# ====================
# FILE UPLOADS
# ====================

FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
ALLOWED_IMAGE_FORMATS       = ['JPEG', 'JPG', 'PNG', 'WEBP']
MAX_IMAGE_SIZE              = 5 * 1024 * 1024  # 5MB


# ====================
# BLOG SETTINGS
# ====================

BLOG_SETTINGS = {
    'POSTS_PER_PAGE': 9,
    'RELATED_POSTS_COUNT': 3,
    'POPULAR_POSTS_COUNT': 5,
    'RECENT_POSTS_COUNT': 5,
    'EXCERPT_LENGTH': 500,
    'META_DESCRIPTION_LENGTH': 160,
    'META_TITLE_LENGTH': 70,
}


# ====================
# EXTERNAL APIs (Placeholder)
# ====================
 
GOOGLE_TAG_MANAGER_ID = config('GOOGLE_TAG_MANAGER_ID', default='GTM-WWL9XFRT')

SOCIAL_LINKS = {
    'facebook':  'https://www.facebook.com/share/1NWKKRnPZX/',
    'instagram': 'https://www.instagram.com/spacesmith_realestate',
    'linkedin':  'https://www.linkedin.com/company/spacesmith-real-estate/',
    'youtube':   'https://youtube.com/@spacesmithrealestate',
    'tiktok':    'https://www.tiktok.com/@spacesmithrealestate',
} 
# reCAPTCHA (if needed)
# RECAPTCHA_SITE_KEY = config('RECAPTCHA_SITE_KEY', default='')
# RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')

SITE_URL = 'https://spacesmith.ae'