# Generated by Django 5.2.16 on 2026-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(help_text="Portrait crop works best (4:5). Export a still frame if it's a Reel.", upload_to='instagram/')),
                ('permalink', models.URLField(blank=True, help_text='Link to the actual Instagram post/reel.')),
                ('caption', models.CharField(blank=True, help_text='Optional — used as image alt text only, not shown on the card.', max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
