# Generated by Django 5.2.16 on 2026-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instagramhighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=25)),
                ('message', models.TextField(blank=True, default='')),
                ('cv', models.FileField(blank=True, null=True, upload_to='career_applications/%Y/%m/')),
                ('source', models.CharField(blank=True, default='Careers — Contact Page', max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='main_career_is_read_40661c_idx'), models.Index(fields=['-created_at'], name='main_career_created_823be8_idx')],
            },
        ),
    ]
